stages:
 - stage: check
   displayName: Compilation check
   dependsOn: []
   jobs:
     - template: azure/cargo-check.yml@templates
       parameters:
         name: cargo_check
         rust: beta
 - stage: test
   displayName: Test suite
   dependsOn: check
   jobs:
     - template: azure/test.yml@templates
       parameters:
         cross: true
         rust: beta
     - template: azure/test.yml@templates
       parameters:
         rust: nightly
         allow_fail: true
 - stage: style
   displayName: Style linting
   dependsOn: check
   jobs:
     - template: azure/rustfmt.yml@templates
       parameters:
         name: rustfmt
         rust: beta
         allow_fail: true
     - template: azure/cargo-clippy.yml@templates
       parameters:
         name: clippy
         rust: beta
         allow_fail: true

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: tower-rs
